version: '3'
services:
  connect4_server:
    image: connect4_server:v1
    volumes:
      - ./src:/connect4_server
    ports:
      - "12345:12345"

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - .data:/data/db